name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v3
      - run: npm --version
      - id: step1
        run: echo "curr_version=$(npm view checkerz version)" >> $GITHUB_OUTPUT
      - run: sudo apt-get install jq
      - id: step2
        run: echo "lodash_version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.step1.outputs.curr_version }}
      - run: echo ${{ steps.step2.outputs.lodash_version }}
    outputs:
      output1: ${{ steps.step1.outputs.curr_version }}
      output2: ${{ steps.step2.outputs.lodash_version }}
  
  job2:
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.output1 == needs.job1.outputs.output2 }}
    needs: job1
    steps:
      - run: echo "Got through"
