# Made a small change to run action.
name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set commit status
      if: ${{ failure() }}
      uses: peter-evans/create-pull-request@v3.11.1
      with:
        commit-message: "Tests failed"
        commit-body: "The tests for this commit have failed."
        branch: "test-failed"
        base: "main"
        title: "Tests failed"
        token: ${{ secrets.GITHUB_TOKEN }}
