name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: npm view checkerz version
      - run: sudo apt-get install jq
      - id: step2
        run: jq -r .version package.json
      - run: ${{ steps.step1 }} >> step.txt
      - run: cat step.txt
      - run: ${{ steps.step1.outputs }}
      - run: echo ${{ steps.step1.outputs.test }}
      - run: echo ${{ steps.step2.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
