name: Publish NPM Package
on: 
  push:
    branches: 'master'
  
jobs:
  check_changes:
    runs-on: ubuntu-latest
    env:
      CHANGED: false
    outputs:
      changed: ${{ env.CHANGED }}
    steps:
      - uses: actions/checkout@v3
      - id: detect_changes
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD package.json)" ]; then
            echo "true"
          fi
      - run: echo ${{ steps.detect_changes.output }}
      - run: echo env
      - run: echo ${{ env.CHANGED }}

  publish-npm:
    needs: check_changes
    runs-on: ubuntu-latest
    if: ${{ needs.check_changes.outputs.changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - run: echo "Ran this ---------------------------------------------------------"
