name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "MY_VARIABLE=some_value" >> $GITHUB_ENV

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.MY_VARIABLE }}
