name: Publish NPM Package
on: 
  push:
    branches: 'master'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
  
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect_changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
      - id: detect_changes
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD package.json)" ]; then
            echo "::set-env name=changed::true"
          else
            echo "::set-env name=changed::false"
          fi
  publish-npm:
    needs: [test, check_changes]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && env.changed }}
    steps:
      - run: echo "Ran this ---------------------------------------------------------"
