name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # Add the following `if` statement to prevent the commit from being pushed if the job fails
    - name: Only push on success
      if: ${{ success() }}
      run: |
        git config --global user.name "vivekjoshi556"
        git config --global user.email "vivekjoshi556@gmail.com"
        git add .
        git commit -m "Test passed"
        git push
