name: Check Version

on:
  push:
    branches:
      - master

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Current Version
        run: echo "::set-env name=CURRENT_VERSION::$(jq -r '.version' package.json)"

      - name: Get Lodash Version
        run: echo "::set-env name=LODASH_VERSION::$(npm view lodash version)"
        
      - name: Set Environment File
        run: |
          echo "CURRENT_VERSION=${{ steps.current-version.outputs.CURRENT_VERSION }}" >> $GITHUB_ENV
          echo "LODASH_VERSION=${{ steps.lodash-version.outputs.LODASH_VERSION }}" >> $GITHUB_ENV


  compare-versions:
    needs: check-versions
    runs-on: ubuntu-latest
    if: ${{ needs.check-versions.result == 'success' && needs.check-versions.outputs.current_version == needs.check-versions.outputs.lodash_version }}
    steps:
      - run: echo ${{ needs.check-versions.outputs.current_version }}
      - run: echo ${{ needs.check-versions.outputs.lodash_version }}
      - name: Run Job
        run: echo "got through"
