name: Publish NPM Package
on: 
  push:
    branches: 'master'
  
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install jq
      - run: ls
      - if: jq.version package.json === npm view lodash version
      - run: echo "Came through"
