name: Publish NPM Package
on: 
  push:
    branches: 'master'
  
jobs:
  test1:
    runs-on: ubuntu-latest
    env:
      CHANGED: false
    outputs:
      changed: ${{ env.CHANGED }}
    steps:
      - uses: actions/checkout@v3
      - id: detect_changes
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD package.json)" ]; then
            echo "true"
          fi
      - run: echo ${{ steps.detect_changes.output }}
      - run: echo env
      - run: echo ${{ env.CHANGED }}

  test2:
    needs: test1
    runs-on: ubuntu-latest
    steps:
      - run: echo github
      - run: sudo apt-get install jq
      - run: jq .version package.json
      - run: echo "Actual Version Present:" && npm view lodash version
