name: Check Version

on:
  push:
    branches:
      - main

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Current Version
        run: echo "::set-output name=current_version::$(jq -r '.version' package.json)"

      - name: Get Lodash Version
        run: echo "::set-output name=lodash_version::$(npm view lodash version)"

  compare-versions:
    needs: check-versions
    runs-on: ubuntu-latest
    if: ${{ needs.check-versions.result == 'success' && needs.check-versions.outputs.current_version == needs.check-versions.outputs.lodash_version }}
    steps:
      - name: Run Job
        run: echo "got through"
